### PR TITLE
Added icon for clipboard fine select

### PR DESCRIPTION
**Pull request by pelya**

### CODE REVIEW

**Comment by menny** [comment]
makes sense. Please also bump https://github.com/AnySoftKeyboard/AnySoftKeyboard-API/blob/master/api/src/main/res/values/version.xml#L3

**Comment by menny** [comment]
and this: https://github.com/AnySoftKeyboard/AnySoftKeyboard-API/blob/master/api/build.gradle#L10

**Comment by pelya** [comment]
Done

**Comment by menny** [comment]
great

**Pull request merged**
